---
domain_name: "20.199.183.9.sslip.io"

db_name: todoapp
db_user: todoapp
db_password: "{{ lookup('env', 'DB_PASSWORD') }}"

db_host: "10.0.2.20"
db_port: 5432
back_host: "10.0.2.10"
back_port: 8080
front_container_port: 3000

image_back: "bayebara01012000/medishop_b"
image_front: "bayebara01012000/medishop_f"
image_tag: "latest"
